version: '3.8'

services:
  prometheus:    
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml      
    ports:
      - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"
    environment:
      HOST: ${HOST}
      TPORT: ${TPORT}
      DPORT: ${DPORT}
    restart: unless-stopped
    networks:
      - monitoring
    
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - prometheus
    ports:
      - "${GRAFANA_PORT}:${GRAFANA_PORT}"
    environment:
      GF_SECURITY_ADMIN_USER: "${MSL_USERNAME}"
      GF_SECURITY_ADMIN_PASSWORD: "${MSL_PASSWORD}"
      GF_USERS_ALLOW_SIGN_UP: "false"  
    networks:
      - monitoring

networks:
  monitoring: