global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'test'
    static_configs:
      - targets: ['${HOST}:${TPORT}']

  - job_name: 'deploy'
    static_configs:
      - targets: ['${HOST}:${DPORT}']